clone:
  depth: 1
build:
  image: golang:1.6
  environment:
    - GAE_SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.36.zip
  commands:
    # lint
    - go get github.com/golang/lint/golint && golint ./...
    # fetch GAE standalone SDK
    - apt-get update -qq && apt-get install -y unzip --no-install-recommends
    - curl -sSLo /tmp/sdk.zip $GAE_SDK_URL && unzip -q -d /tmp /tmp/sdk.zip
    - export PATH=/tmp/go_appengine:$PATH
    # latest package deps
    - go get -d google.golang.org/appengine
    - go get -d ./...
    # test
    - cp server/config.json.sample server/config.json
    - go test ./...
