clone:
  depth: 1
build:
  image: golang
  environment:
    - GAE_SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.30.zip
  commands:
    # standalone GAE sdk
    - apt-get update -qq && apt-get install -y unzip --no-install-recommends
    - curl -sSLo /tmp/sdk.zip $GAE_SDK_URL && unzip -q -d /tmp /tmp/sdk.zip
    # latest package deps
    - go get -d google.golang.org/appengine
    - go get -d ./...
    # test
    - cp server/config.json.sample server/config.json
    - /tmp/go_appengine/goapp test ./...
    # lint
    - go get github.com/golang/lint/golint && golint ./...
